TESTS WITH ERRORS 
test02 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/gradingtests.py", line 26, in test02
    actual = self.KB.kb_explain(read.parse_input("rule: ((contains bowl flour) (contains bowl water)) -> (contains bowl wetFlour)"))
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/student_code.py", line 162, in kb_explain
    if not self.kb_ask(s): print("Rule is not in the KB")
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/student_code.py", line 116, in kb_ask
    print("Invalid ask:", fact.statement)
AttributeError: 'Rule' object has no attribute 'statement'

test03 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/gradingtests.py", line 73, in test03
    actual = self.KB.kb_explain(fact4)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/student_code.py", line 166, in kb_explain
    x = x + helper(n)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/student_code.py", line 175, in helper
    blah = "    rule: " +  "(" + str(fr.lhs) + ")->" + str(fr.rhs[0]) + "\n"
AttributeError: 'list' object has no attribute 'lhs'

-------------------------------
TESTS FAILED  
test01 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/gradingtests.py", line 23, in test01
    self.compare("Fact is not in the KB", actual)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/gradingtests.py", line 18, in compare
    '"{0}" ({1} lead spaces)'.format(a, len(a) - len(a.strip())))
AssertionError: '"Fact is not in the KB" (0 lead spaces)' != '"fact: (notContains kb fact)" (0 lead spaces)'
- "Fact is not in the KB" (0 lead spaces)
+ "fact: (notContains kb fact)" (0 lead spaces)


test04 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/gradingtests.py", line 136, in test04
    self.compare(self.expected, actual)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference-ec/gradingtests.py", line 18, in compare
    '"{0}" ({1} lead spaces)'.format(a, len(a) - len(a.strip())))
AssertionError: '"    fact: (eats herbivore leaves) ASSERTED" (4 lead spaces)' != '"" (0 lead spaces)'
- "    fact: (eats herbivore leaves) ASSERTED" (4 lead spaces)
+ "" (0 lead spaces)


-------------------------------
TESTS SKIPPED 
-------------------------------
